# Usar una imagen base de Node.js con la versión mínima requerida
FROM node:18.19.0 AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Construir la aplicación
RUN npm run build

# Usar una imagen base de Nginx para servir la aplicación
FROM nginx:alpine

# Copiar el contenido de la carpeta dist/pedido-reto al directorio de Nginx
COPY --from=build /app/dist/pedido-reto /usr/share/nginx/html